Step6
loki1520/frontend-project-46 pull request #10
Opened 2023-09-14 07:12 UTC by loki1520

2023-09-14 08:57 UTC, CoraloReef commented on src/getTree.js
> +      value1: obj1[key],
Пршлый раз зыбыл написать, но глядя на код приходится задумываться что за значение 1 и 2 и каое из них новое, а какое старое

2023-09-14 08:59 UTC, CoraloReef commented on src/stylish.js
> +    return `${currentValue}`;
Нужна ли здесь интерполяция?

2023-09-14 09:03 UTC, loki1520 commented on src/getTree.js
> +      value1: obj1[key],
да, поправил :  valueDeleted, valueAdded

2023-09-14 09:04 UTC, CoraloReef commented on src/stylish.js
> +      switch (obj.type) {
Здесь тоже можно деструктуризацию сделать)

2023-09-14 09:04 UTC, CoraloReef commented on src/stylish.js
> +      switch (obj.type) {
Но по желанию

2023-09-14 09:05 UTC, loki1520 commented on src/stylish.js
> +    return `${currentValue}`;
да, т.к. нам нужен строковый вывод, иначе если будет число или другой тип - он выведет "не строку"

2023-09-14 09:07 UTC, CoraloReef commented on src/stylish.js
> +    return `${currentValue}`;
Есть более очевидные способы приведения к строке

2023-09-14 09:12 UTC, loki1520 commented on src/stylish.js
> +      switch (obj.type) {
сделал, но не получилось ли больше сумятицы?
перепроверь пожалуйста, ты так имел ввиду?)

2023-09-14 09:14 UTC, loki1520 commented on src/stylish.js
> +    return `${currentValue}`;
намек понял, надеюсь правильно, исправил

2023-09-14 09:16 UTC, loki1520 commented on src/stylish.js
> +      switch (obj.type) {
да, может опыта мне не хватает, но для меня, так код теряет в "очевидности", приходится добавлять вообще все свойства, в некоторых объектах их нет (valueDeleted, valueAdded)

2023-09-14 09:30 UTC, CoraloReef commented on src/stylish.js
> +      switch (obj.type) {
А я не вижу изменений тут) Может и правда хуже, но не видно

2023-09-14 21:35 UTC, CoraloReef approved these changes

2023-09-14 21:38 UTC, CoraloReef commented on src/stylish.js
> +const getIndentEnd = (depth) => ' '.repeat(depth * 4 - 4);
Что-то совсем лишнее

2023-09-14 21:38 UTC, CoraloReef commented on src/stylish.js
> +    return `${currentValue}`;
Снова интерполяция?

2023-09-14 21:40 UTC, CoraloReef requested changes
Почему вернулась интерполяция для приведения к string? 
getIndentEnd кажется лишним

2023-09-15 02:22 UTC, loki1520 commented on src/stylish.js
> +const getIndentEnd = (depth) => ' '.repeat(depth * 4 - 4);
да, убрал

2023-09-15 02:25 UTC, loki1520 commented on src/stylish.js
> +    return `${currentValue}`;
пардон, отмотал назад лишнее..(((

2023-09-15 05:04 UTC, merged