Step7
loki1520/frontend-project-46 pull request #12
Opened 2023-09-15 10:00 UTC by loki1520

2023-09-15 21:53 UTC, CoraloReef requested changes
Test

2023-09-17 21:07 UTC, CoraloReef commented on src/formatters/index.js
> +  if (format === 'plain') {
Вот здесь очень напрашивается деструктуризация

2023-09-17 21:09 UTC, CoraloReef commented on src/formatters/plain.js
> +  if (obj.type === 'nested') {
Давай единообразно, в соседнем формате свитч, а тут ифы. Лучше привести к одному стилю - свитчи или лучше деструктуризации

2023-09-17 21:10 UTC, CoraloReef commented on src/formatters/plain.js
> +const getWay = (data, path = '') => data.reduce((acc, obj) => {
Интересное название функции, но ладно, спорить не буду)

2023-09-17 21:11 UTC, CoraloReef commented on src/formatters/plain.js
> +const plain = (obj1, obj2) => {
Название функции - отвечает на вопрос что она делает, тут не понятно

2023-09-17 21:12 UTC, CoraloReef commented on src/formatters/stylish.js
> +  const getRender = (array, depth = 1) => {
лучше не пользоваться такими именами array, что в массиве?

2023-09-18 04:23 UTC, loki1520 commented on src/formatters/index.js
> +  if (format === 'plain') {
Исправил

2023-09-18 05:11 UTC, loki1520 commented on src/formatters/plain.js
> +  if (obj.type === 'nested') {
черддд, в локальном черновике уже сделано свичем, забыл перенести, исправлено.

2023-09-18 05:13 UTC, loki1520 commented on src/formatters/plain.js
> +const getWay = (data, path = '') => data.reduce((acc, obj) => {
тогда не буду трогать, а то сделаю так что будет ошибка)

2023-09-18 05:25 UTC, loki1520 commented on src/formatters/plain.js
> +const getWay = (data, path = '') => data.reduce((acc, obj) => {
Да, ты прав, мы не путь получаем, а строки (или линии, как в stylish.js).
Исправил.

2023-09-18 05:35 UTC, loki1520 commented on src/formatters/plain.js
> +const plain = (obj1, obj2) => {
Поменял на getPlainFormat, но импорты оставил, вроде так просили в задании:
"Реализуйте возможность выбора формата plain. Функция сравнения должна иметь параметр, выбирающий вид представления результата.".
Я думал сама директория formatters указывает на то что это мы выбираем форматы вывода.)
или везде эту функцию во всех импортах нужно переименовать?

2023-09-18 05:39 UTC, loki1520 commented on src/formatters/stylish.js
> +  const getRender = (array, depth = 1) => {
Поменял

2023-09-18 05:50 UTC, loki1520 commented on src/formatters/stylish.js
> +  const getRender = (array, depth = 1) => {
treeAST

2023-09-18 14:58 UTC, CoraloReef commented on src/formatters/plain.js
> +const lines = (data, path = '') => data.reduce((acc, obj) => {
getLines?

2023-09-18 15:00 UTC, CoraloReef commented on src/formatters/plain.js
> +const plain = (obj1, obj2) => {
Речь только о названии функции, дальнейшие импорты - это другое

2023-09-18 15:14 UTC, loki1520 commented on src/formatters/plain.js
> +const lines = (data, path = '') => data.reduce((acc, obj) => {
facepalm::
исправил

2023-09-18 16:19 UTC, CoraloReef approved these changes

2023-09-18 16:28 UTC, merged