Step3
loki1520/frontend-project-46 pull request #5
Opened 2023-08-30 04:49 UTC by loki1520

2023-09-03 13:57 UTC, CoraloReef commented on src/comparison.js
> +  keys.map((key) => {
От метода map ожидается, что будет преобразование массива. Здесь этого не происходит

2023-09-03 13:58 UTC, CoraloReef commented on src/comparison.js
> +  let result = '';
Это нарушает условие задание, которое называется "Иммутабельность" :)

2023-09-03 14:00 UTC, CoraloReef requested changes
Должна быть Иммутабельность

2023-09-04 21:31 UTC, CoraloReef commented on src/index.js
> +// const getFileExtention = (filepath) => filepath.slice(filepath.lastIndexOf('.') + 1);
Глянь на path.extname

2023-09-04 21:33 UTC, CoraloReef commented on src/comparison.js
> +  const getTree = keys.map((key) => {
Зачем эту функцию нужно держать внутри другой функции?

2023-09-04 21:34 UTC, CoraloReef commented on src/comparison.js
> +const comparison = (obj1, obj2) => {
Переводится как сравнение? Не очень подходящее название для функции, не?

2023-09-05 05:09 UTC, loki1520 commented on src/index.js
> +// const getFileExtention = (filepath) => filepath.slice(filepath.lastIndexOf('.') + 1);
да, действительно проще), переделал

2023-09-05 05:50 UTC, loki1520 commented on src/comparison.js
> +  const getTree = keys.map((key) => {
пардон, не как отмазка: но я помню что надо все разносить по отдельным блокам, там просто в задании сказали что сильно не нужно раскидывать пока кода мало, думал оставить, может потом подвох будет))

2023-09-05 05:52 UTC, loki1520 commented on src/comparison.js
> +const comparison = (obj1, obj2) => {
да, функция должна быть глаголом: findObjectDifferences, вот что придумал))

2023-09-05 08:19 UTC, CoraloReef commented on src/getTree.js
> +  const result = keys.map((key) => {
Здесь не нужна доп константа, можно просто `return keys.map((key) => {...`

2023-09-05 08:21 UTC, CoraloReef commented on src/findObjectDifferences.js
> +const findObjectDifferences = (obj1, obj2) => {
Хм, функция поиска отличий? Мне кажется по факту она рендерит AST. Может просто render?

2023-09-05 08:22 UTC, CoraloReef commented on src/findObjectDifferences.js
> +  const prepairedTree = getTree(obj1, obj2);
Тут тоже не обязательно усложнять, может `const tree =` или `const ast =`?

2023-09-05 08:24 UTC, CoraloReef commented on src/comparison.js
> +  const getTree = keys.map((key) => {
А тут не разносить по блокам, можно было просто вынести ее за предел comparison. Иначе функция getTree будет каждый раз создаваться при вызове comparison

2023-09-05 08:28 UTC, loki1520 commented on src/getTree.js
> +  const result = keys.map((key) => {
исправлено

2023-09-05 08:29 UTC, loki1520 commented on src/findObjectDifferences.js
> +const findObjectDifferences = (obj1, obj2) => {
ок, render!

2023-09-05 08:29 UTC, loki1520 commented on src/findObjectDifferences.js
> +  const prepairedTree = getTree(obj1, obj2);
ок

2023-09-05 08:32 UTC, loki1520 commented on src/comparison.js
> +  const getTree = keys.map((key) => {
ок, понял, но уже сделал "с запасом"))

2023-09-05 08:53 UTC, CoraloReef approved these changes

2023-09-05 15:12 UTC, merged